[package]
name = "id3-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.37", features = ["derive"] }
id3 = "1.16.2"
once_cell = "1.21.3"
predicates = "3.1.3"
